# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: BH CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  brian:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache : 'npm'
      - name : 'Hello World'
        run : echo "Ola de mar"
      - name : Dime la fecha
        run : date
      - name : muestra el contenido del directorio
        run : ls -la
        
      - run : npm ci --legacy-peer-deps --no-fund --no-audit
      - run : npm run lint
      - run : npm run build
